### ISSUE TITLE
Incorrect information about the lack of a Makefile

### ISSUE THREAD

**Issue by andrewrothman** [alandekok/jlibtool#1]
In the README, the following text is found:

> "There is no configure script. None is needed. There is no Makefile. None is needed."

A few lines below, the following text is found:

> "Just use make, which is smart enough to figure out how to build C programs:"

At this point I was very confused. To keep my sanity in check, I looked for a Makefile and there was one included in the repository.

**Comment by alandekok** [comment]
If you read the Makefile, you'll see it has many examples of using jlibtool.

It doesn't REQUIRE a Makefile.  But if CAN use one, if it exists.

I fail to see how this is an issue in anything other then comprehension.

**Comment by andrewrothman** [comment]
I'm not quite sure what you mean that it doesn't require one. I ran this in terminal and got this output:

> AndyBook:Desktop AndyRoth$ git clone https://github.com/alandekok/jlibtool.git
> Cloning into 'jlibtool'...
> remote: Counting objects: 293, done.
> remote: Compressing objects: 100% (192/192), done.
> remote: Total 293 (delta 166), reused 212 (delta 85)
> Receiving objects: 100% (293/293), 66.18 KiB, done.
> Resolving deltas: 100% (166/166), done.
> AndyBook:Desktop AndyRoth$ cd jlibtool
> AndyBook:jlibtool AndyRoth$ rm Makefile
> AndyBook:jlibtool AndyRoth$ make
> make: **\* No targets specified and no makefile found.  Stop.
> AndyBook:jlibtool AndyRoth$ 

Also, yes, this is an issue regarding only comprehension. I just want to find out what you mean by it not requiring a Makefile.

**Comment by alandekok** [comment]
Most modern "make" programs have internal rules which tell them how to build binaries from C files.  Those "make" programs don't need explicit Makefiles.

I really don't understand your need for pedantic clarity.  You're confused that it does _need_ a Makefile, but it uses one if one exists?  Why in gods green earth is this an issue to worry about, much less complain repeatedly about?

**Comment by andrewrothman** [comment]
I'm sorry to trouble you. I was just trying to understand. This is totally not an issue to worry about. If this were a problem in the documentation then it would benefit others to have it corrected but I see that this is not the case. Thank you for clarifying this to me and thank you for your time.
