### ISSUE TITLE
recommendation of using dlopen() from statically linked programs is bogus

### ISSUE THREAD

**Issue by rofl0r** [alandekok/jlibtool#3]
musl libc does not even implement dlopen() for statically linked programs, since it imposes a number of serious problems[1].

[1] http://openwall.com/lists/musl/2012/12/08/4 response of musl libc's author to a question asked about the topic

**Comment by alandekok** [comment]
If your goal is to have a binary that has no external dependencies, then you're not going to use dlopen() at all.  Instead (as they say), you'll just statically link it.

For pretty much every other situation, the binaries will be compiled for a particular system.  In those cases, using dynamic libraries is almost always beneficial.

**Comment by rofl0r** [comment]
if the advantages of dynamic linking outbalance statical linking depends on the specific scenario, and there are numerous discussions about the topic with no clear winner. so boldly recommending dynamic linking is highly biased and has no business in a README.

but back to the topic, you recommend in your README to use statical linked binaries that use dlopen(), which is completely bogus, as can be read in the above link.
